# docker-compose.yml

## https://gist.github.com/leopoldodonnell/b0b7e06943bd389560184d948bdc2d5b
## Etensions: pgcrypto, https://github.com/michelp/pgjwt
 
version: '3'

services:

  postgrest:
    restart: always
    image: "postgrest/postgrest:${POSTGREST_VERSION}"
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres" #BWI_${DB_VERSION}_${DB_VERSION_POSTFIX}
      #PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: ${POSTGRES_USER} #In production this role should NOT be the same as the one used for the connection
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
      PGRST_DB_PRE_CONFIG: "postgrest.pre_config"

    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres:${POSTGRES_VERSION}"
    ports:
        - "5432:5432"
    environment:

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

      POSTGRES_EXTENSIONS: pgcrypto, pgjwt

    volumes:
      

      - ./pgjwt/extension/pgjwt.control:/usr/share/postgresql/16/extension/pgjwt.control
      - ./pgjwt/extension/pgjwt--0.2.0-tfm.sql:/usr/share/postgresql/16/extension/pgjwt--0.2.0.sql

      

      - ./pgjwt/authentication.sql:/docker-entrypoint-initdb.d/authentication.sql
      - ./pgjwt/users.sql:/docker-entrypoint-initdb.d/users.sql

      #- ./schemas:/docker-entrypoint-initdb.d

      - ./api.sql:/docker-entrypoint-initdb.d/api.sql

      - ./config/postgrest.sql:/docker-entrypoint-initdb.d/postgrest.sql

      - ../ci2027-db-structure/v001/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      
      #- ../ci2027-db-structure/default.sql:/docker-entrypoint-initdb.d/default.sql

      - ./postgres-data:/docker-entrypoint-initdb.d

  pgadmin:
    restart: always
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "5050:80"
    links:
        - "postgres:${PGADMIN_HOST_NAME}"
    depends_on:
      - postgres
    #volumes:
    #  - pgadmin-data:/var/lib/pgadmin

  swagger:
    restart: always
    image: swaggerapi/swagger-ui
    ports:
        - "8080:8080"
    expose:
        - "8080"
    environment:
        API_URL: http://127.0.0.1:3000/
    depends_on:
      - postgrest
#volumes:
#  db-data:
#  pgadmin-data: