# docker-compose.yml
# https://gis-ops.com/de/postgrest-tutorial-installation-and-setup/
 
services:

  postgrest:
    restart: no
    image: "postgrest/postgrest:v12.0.2"
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgis"
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: ${PGRST_OPENAPI_SERVER_PROXY_URI}
      PGRST_DB_PRE_CONFIG: "postgrest.pre_config"
      PGRST_OPENAPI_SECURITY_ACTIVE: "true"
      
    depends_on:
      - postgres


  postgres:
    restart: no
    image: "kartoza/postgis"
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=postgis
  
    volumes:

      # pgjwt & pgcrypto Extension
      - ./pgjwt/pgjwt.control:/usr/share/postgresql/13/extension/pgjwt.control
      - ./pgjwt/pgjwt--0.2.0-tfm.sql:/usr/share/postgresql/13/extension/pgjwt--0.2.0.sql
      - ./pgcrypto.sql:/docker-entrypoint-initdb.d/30-pgcrypto.sql
      - ./postgrest-config.sql:/docker-entrypoint-initdb.d/11-postgrest-config.sql

      # Postgrest Permission Management
      - ./postgres/impex.sql:/docker-entrypoint-initdb.d/10-impex.sql
      #- ./postgres/view.sql:/docker-entrypoint-initdb.d/11-view.sql
      - ./postgres/import-fn.sql:/docker-entrypoint-initdb.d/12-view-get.sql
      - ./postgres/export-fn.sql:/docker-entrypoint-initdb.d/13-export-fn.sql
      
      # - ./pgdata:/var/lib/postgresql/data

  # https://hub.docker.com/r/prodrigestivill/postgres-backup-local

  pgadmin:
    restart: no
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: 5050
        SCRIPT_NAME: "/pgadmin"
    ports:
        - "5050:5050"
    links:
        - postgres:${PGADMIN_HOST_NAME}
    depends_on:
      - postgrest
    user: root
    volumes:
      - ./pgadmindata:/var/lib/pgadmin

