name: Docker Compose Actions Workflow

on: push

jobs:

  test:
  
    runs-on: ubuntu-latest
    
    steps:
      # https://github.com/orgs/community/discussions/28672
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Clone private repo
        run: git clone "https://git-dmz.thuenen.de/datenerfassungci2027/ci2027_datenerfassung/ci2027-db-data.git" ci2027-db-data
        env:
          EXTERNAL_TOKEN : ${{ secrets.GITLAB_TOKEN }}

        
      - name: Build the stack
        run: docker-compose --env-file _.env up -d

      - name: Install dependencies
        run: npm ci
        
      - name: Connect to PostgreSQL
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data
        run: node test/basic.js
        # Environment variables used by the `client.js` script to create
        # a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
